name: hasia2
channels:
  - conda-forge
  - defaults  
dependencies:
  - python=3.7
  - pip=22.0.4
  - numpy=1.21.1
  - scipy=1.7.0
  - matplotlib=3.3.4
  - pandas=1.3.1
  - netcdf4=1.5.6
  - xarray=0.20.2
  - dask=2021.2.0
  - bottleneck=1.3.2
  - cartopy=0.19.0.post1
  - seaborn=0.11.1
  - cmocean=2.0
  - metpy=1.2.0
  - ipykernel=5.5.5
  - jupyter=1.0.0
  - ffmpeg=4.3.2
  - wrf-python=1.3.2.5
  - bs4=4.10.0
  - plotly=5.11.0
  - xoak
  - pip:
    - boto3==1.21.28
    - requests==2.25.1
