# Filename:    ERA5_config.yml
# Author:      Deanna Nash, dlnash@ucsb.edu
# Description: Dictionary of different download variables/options for ERA5 - for use in conjunction with getERA5_batch.py

---
ivt: 
    data_type: 'reanalysis-era5-single-levels'
    levels: 'OFF'
    var_name: ['vertical_integral_of_northward_water_vapour_flux', 'vertical_integral_of_eastward_water_vapour_flux']
    start_yr: 1979
    end_yr: 2019
    month: ['01','02','03','04','05','06','07','08','09','10','11','12']
    day: ['01','02','03','04','05','06', '07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
    time: ['00:00','06:00','12:00','18:00']
    area: [60, 0, 0, 120] # [N,W,S,E] Default: global
    grid: [0.5, 0.5]
    datadir: '/home/sbarc/students/nash/data/ERA5/ivt/6hr/'
    fprefix: 'era5_hma_05dg_6hr_ivt'
    
prec:
    data_type: 'reanalysis-era5-single-levels'
    levels: 'OFF'
    var_name: ['mean_total_precipitation_rate']
    start_yr: 1979
    end_yr: 2019
    month: ['01','02','03','04','05','06','07','08','09','10','11','12']
    day: ['01','02','03','04','05','06', '07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
    time: ['00:00','06:00','12:00','18:00']
    area: [60, 0, 0, 120] # [N,W,S,E] Default: global
    grid: [0.25, 0.25]
    datadir: '/home/sbarc/students/nash/data/ERA5/prec/6hr/'
    fprefix: "era5_hma_025dg_6hr_prec"
    
huvq:
    data_type: 'reanalysis-era5-pressure-levels'
    var_name: ['geopotential', 'specific_humidity', 'u_component_of_wind', 'v_component_of_wind']
    levels: ['250']
    start_yr: 1979
    end_yr: 2019
    month: ['01','02','03','04','05','06','07','08','09','10','11','12']
    day: ['01','02','03','04','05','06', '07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
    time: ['00:00','06:00','12:00','18:00']
    area: [60, 0, -15, 120] # [N,W,S,E] Default: global
    grid: [0.5, 0.5]
    datadir: '/home/sbarc/students/nash/data/ERA5/huvq/6hr/'
    fprefix: "era5_hma_05dg_6hr_huvq"
    
ivt_case_201002:
    data_type: 'reanalysis-era5-single-levels'
    levels: 'OFF'
    var_name: ['vertical_integral_of_northward_water_vapour_flux', 'vertical_integral_of_eastward_water_vapour_flux', 'mean_total_precipitation_rate']
    start_yr: 2010
    end_yr: 2010
    month: ['02']
    day: ['04', '05','06','07','08','09']
    time: ['00:00', '01:00', '02:00', '03:00', '04:00', '05:00', '06:00', '07:00', '08:00', '09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00', '21:00', '22:00', '23:00']
    area: [50, 0, 0, 110] # [N,W,S,E] Default: global
    grid: [0.25, 0.25]
    datadir: '/home/sbarc/students/nash/data/ERA5/'
    fprefix: "era5_hma_025deg_1hr_ivt_201002"
    
ivt_case_200201:
    data_type: 'reanalysis-era5-single-levels'
    levels: 'OFF'
    var_name: ['vertical_integral_of_northward_water_vapour_flux', 'vertical_integral_of_eastward_water_vapour_flux', 'mean_total_precipitation_rate']
    start_yr: 2002
    end_yr: 2002
    month: ['01']
    day: ['10', '11','12','13','14']
    time: ['00:00', '01:00', '02:00', '03:00', '04:00', '05:00', '06:00', '07:00', '08:00', '09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00', '21:00', '22:00', '23:00']
    area: [50, 0, 0, 110] # [N,W,S,E] Default: global
    grid: [0.25, 0.25]
    datadir: '/home/sbarc/students/nash/data/ERA5/'
    fprefix: "era5_hma_025deg_1hr_ivt_200201"
    
250z_case_201002:
    data_type: 'reanalysis-era5-pressure-levels'
    levels: ['250']
    var_name: ['geopotential']
    start_yr: 2010
    end_yr: 2010
    month: ['02']
    day: ['04', '05','06','07','08','09']
    time: ['00:00', '01:00', '02:00', '03:00', '04:00', '05:00', '06:00', '07:00', '08:00', '09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00', '21:00', '22:00', '23:00']
    area: [50, 0, 0, 110] # [N,W,S,E] Default: global
    grid: [0.25, 0.25]
    datadir: '/home/sbarc/students/nash/data/ERA5/'
    fprefix: "era5_hma_025deg_1hr_250z_201002"
    
250z_case_200201:
    data_type: 'reanalysis-era5-pressure-levels'
    levels: ['250']
    var_name: ['geopotential']
    start_yr: 2002
    end_yr: 2002
    month: ['01']
    day: ['10', '11','12','13','14']
    time: ['00:00', '01:00', '02:00', '03:00', '04:00', '05:00', '06:00', '07:00', '08:00', '09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00', '21:00', '22:00', '23:00']
    area: [50, 0, 0, 110] # [N,W,S,E] Default: global
    grid: [0.25, 0.25]
    datadir: '/home/sbarc/students/nash/data/ERA5/'
    fprefix: "era5_hma_025deg_1hr_250z_200201"
...